### ISSUE TITLE
npm update needed?

### ISSUE THREAD

**Issue by anetz89** [plepe/overpass-frontend#1]
Hi there,
great job so far! I wonder why your package is not popular...
I installed your npm  package and it seems like the latest version of your repository is not available.

The following lines (in OverpassFrontent.js) breaks my code:
```
function toQuadtreeLookupBox (boundingbox) {
  return new Quadtree.Box(
    new Quadtree.Point(boundingbox.bounds.minlat, boundingbox.bounds.minlon),
    new Quadtree.Point(boundingbox.bounds.maxlat, boundingbox.bounds.maxlon)
  )
}
```
as boundingbox.bounds is not defined.
Your repository seems to fix this problem already (removing ".bounds" and access min/maxlon/lat direclty).

Can you update the package? Thanks in advance!

**Comment by plepe** [comment]
The package is rather new, I developed it for my ptmap project. I'll try to build a new npm package soon, first I'll check that all tests are working ...

**Comment by anetz89** [comment]
No worries. To be honest, I switched to [query-overpass](https://www.npmjs.com/package/query-overpass), as it is more lightweight. Maybe it is helpful for your project, too. 
Thanks!
