### ISSUE TITLE
unable to build master

### ISSUE THREAD

**Issue by michelelaporta** [plepe/overpass-frontend#10]
Step to reproduce:

git clone https://github.com/plepe/overpass-frontend.git
cd overpass-frontend
npm install --save overpass-frontend

npm ERR! Cannot read property 'match' of undefined

`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@6.12.1
3 info using node@v10.16.0
4 verbose npm-session df627f5f495a95bd
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall overpass-frontend@2.4.3
7 info lifecycle overpass-frontend@2.4.3~preinstall: overpass-frontend@2.4.3
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 8ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 http fetch GET 200 https://registry.npmjs.org/boundingbox 12ms (from cache)
16 silly pacote version manifest for boundingbox@1.1.0 fetched in 17ms
17 timing stage:rollbackFailedOptional Completed in 1ms
18 timing stage:runTopLevelLifecycles Completed in 90ms
19 silly saveTree overpass-frontend@2.4.3
19 silly saveTree ├─┬ @turf/bbox-clip@6.0.3
19 silly saveTree │ ├── @turf/helpers@6.1.4
19 silly saveTree │ └── @turf/invariant@6.1.2
19 silly saveTree ├─┬ @turf/difference@6.0.2
19 silly saveTree │ ├─┬ @turf/area@6.0.1
19 silly saveTree │ │ └── @turf/meta@6.0.2
19 silly saveTree │ ├── @turf/meta@6.0.2
19 silly saveTree │ └── martinez-polygon-clipping@0.4.3
19 silly saveTree ├─┬ @turf/intersect@6.1.3
19 silly saveTree │ └── martinez-polygon-clipping@0.4.3
19 silly saveTree ├─┬ @turf/union@6.0.3
19 silly saveTree │ └── martinez-polygon-clipping@0.4.3
19 silly saveTree ├── async@2.6.2
19 silly saveTree └── boundingbox@1.1.0
20 verbose stack TypeError: Cannot read property 'match' of undefined
20 verbose stack     at tarballToVersion (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
20 verbose stack     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
20 verbose stack     at BB.each (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
20 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
20 verbose stack     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
20 verbose stack     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
20 verbose stack     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
20 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
20 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
20 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
20 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
20 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
20 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
20 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
20 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
20 verbose stack     at runCallback (timers.js:705:18)
21 verbose cwd /home/michele/workspace/overpass-frontend
22 verbose Linux 5.0.0-35-generic
23 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
24 verbose node v10.16.0
25 verbose npm  v6.12.1
26 error Cannot read property 'match' of undefined
27 verbose exit [ 1, true ]

`

**Comment by plepe** [comment]
Thanks for notifying! The package-lock.json file was broken. I already pushed an up-to-date version to master, so please try again!
