### ISSUE TITLE
single point tags

### ISSUE THREAD

**Issue by lukasa1993** [plepe/overpass-frontend#18]
what is best way to get single point tags ? single long lat

**Comment by plepe** [comment]
Do you know the ID?

Then you can use:
```js
overpassFrontend.get(
  'n1234',
  {
     properties: OverpassFrontend.GEOM|OverpassFrontend.TAGS
  },
  function (err, result) {
    console.log('* ' + result.tags.name + ' (' + result.id + ')')
  },
  function (err) {
    if (err) { console.log(err) }
  }
)
```

I'll improve the README, because this is a common use-case.

**Comment by lukasa1993** [comment]
@plepe id of what? i just have longitude and latitude. thanks for quick response

**Comment by plepe** [comment]
Oh, I see. You can use this (in fact the same query as in the README, but with 'node' as query and a smaller bbox):

```js
overpassFrontend.BBoxQuery(
  'node',
  { minlat: 48.1900, maxlat: 48.1901, minlon: 16.3300, maxlon: 16.3301 },
  {
    properties: OverpassFrontend.ALL
  },
  function (err, result) {
    console.log('* ' + result.tags.name + ' (' + result.id + ')')
  },
  function (err) {
    if (err) { console.log(err) }
  }
)
```

**Comment by lukasa1993** [comment]
how i calculate bbox from single longitude and latitude? whatever i try result is overwhelming 100+

**Comment by plepe** [comment]
Substract/add circa 0.00001.

XKCD has a good comic about precision on coordinates: https://xkcd.com/2170/

**Comment by lukasa1993** [comment]
thank you

**Comment by lukasa1993** [comment]
@plepe can i request larger box like 0.01 and grab nearest first ?

**Comment by plepe** [comment]
No, this is not possible. There's no order in the results, also the bbox does not have a distance (just inside/intersecting/outside).

Even pure Overpass QL wouldn't have a query like this: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL

(overpass-frontend uses a simplified version of Overpass QL for caching results - so if you run the query again, it will return the result instantly; if the query is different it will return matching, cached elements directly and request only further objects).
