### ISSUE TITLE
npm package is 22MB?

### ISSUE THREAD

**Issue by nornagon** [plepe/overpass-frontend#20]
```
 19M	node_modules/overpass-frontend/dist/test.js
```

looks like that could maybe be excluded from the npm package?

**Comment by plepe** [comment]
You are right, I will do that.

**Comment by plepe** [comment]
(Should be) fixed in 7c9ac144171afe947929066772e08121c5f08c69

**Comment by plepe** [comment]
No, that didn't work, as I was already using the 'files' property in package.json (I'm not doing that so often). Fixed again in 1d04fc8c5663d2af8ce0642a074733d98b28ef0d -> version 2.6.1.

**Comment by plepe** [comment]
What do you think, I also removed the `doc/` directory. Should the documentation be included in the npm package?

**Comment by nornagon** [comment]
I think that's a matter of opinion, but I'd personally lean towards no.
