### ISSUE TITLE
how to add options to api-request? (limit to 10 entries)

### ISSUE THREAD

**Issue by vanderbreye** [plepe/overpass-frontend#27]
i would like to limit the request to return 10 entries to speed up everything.

**Comment by plepe** [comment]
I added an option 'limit' to BBoxQuery, included in the release 3.1.0.

Example:
```js
overpassFrontend.BBoxQuery(
  'nwr[amenity=restaurant]',
  { minlat: 49, minlon: 15, maxlat: 50, maxlon: 16 },
  { limit: 10 },
  (err, feature) => console.log(feature.id),
  (err) => console.log('finish')
)
```

**Comment by plepe** [comment]
Damn, I found a little bug, so I had to made another patch release. Use 3.1.1 instead.

**Comment by vanderbreye** [comment]
thank you!
did implement it, seems to work!
