### ISSUE TITLE
wish: example doc for fetching a relation as GeoJSON based on ID

### ISSUE THREAD

**Issue by markstos** [plepe/overpass-frontend#31]
Given an OSM for a relation that is a city boundary, I would like to get the city boundary back as GeoJSON.

No Bounding box will be provided-- I'm trying to make a generic query tool that could work anyway.

I found the `get` method to get based on an  id. I can see it returns a `members` array, but when I call the GeoJSON method, the geometries array is empty.

It would be great if the docs could cover how to get back GeoJSON that takes into account all the members of a relation in a case like this.

**Comment by plepe** [comment]
Yes, I see that this is confusing in the README. You have to set the `properties` option to a value which includes the geometry of the item. I added a section in the README: 7f8f2f780b14fded03ede688dc8c171f94afd16b

I hope this is clearer now. If you have suggestions for improvements, they are very welcome!

**Comment by markstos** [comment]
I see the new docs here: https://github.com/plepe/overpass-frontend/commit/9c1d6a08dbe2114e9d529eb367c49981a9306e4f

Yes, that's clearer, thanks!
