### ISSUE TITLE
effortPerRequest meaning unclear

### ISSUE THREAD

**Issue by matkoniecz** [plepe/overpass-frontend#7]
https://rawgit.com/plepe/overpass-frontend/master/doc/OverpassFrontend.html

> To avoid huge requests to the Overpass API, the request will be split into smaller chunks. This value defines, at which effort the request will be sent.

At least it would useful to know whatever greater or smaller values are more aggressive.

**Comment by plepe** [comment]
I hope, it's better now? The larger effortPerRequest, the more items will be requested from Overpass API per call.

**Comment by matkoniecz** [comment]
Yes, thanks!
