### ISSUE TITLE
Error loading file RangeError [ERR_FS_FILE_TOO_LARGE]

### ISSUE THREAD

**Issue by Connum** [plepe/overpass-frontend#9]
I'm trying out the example code, but instead of using the API, I'm trying to open a file `germany-latest.osm.bz2` that I got from here: http://download.geofabrik.de/europe.html

It's about 5 GB big, and results in the following error:
> Error loading file RangeError [ERR_FS_FILE_TOO_LARGE]: File size (5205413005) is greater than possible Buffer: 2147483647 bytes
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:264:11)

Would it be possible to change file handling to streams instead of loading everything into a buffer?

**Comment by plepe** [comment]
overpass-frontend started as a in-browser data cache, the functionality to load XML files was added later as a by-product. In fact, I don't think, that the code is optimized enough for large datasets. Maybe you start to test with the data of a city or so?

Anyway, I'll be happy to merge any pull requests which enable loading larger datasets :-)

**Comment by Connum** [comment]
Servus!
I'll try to integrate [`node-osm-stream` ](https://www.npmjs.com/package/node-osm-stream) and see how that goes. Happy to send a PR if it's successful.

**Comment by plepe** [comment]
Sorry for not replying earlier. node-osm-stream sounds quite nice - it could be possible to replace the XML parser with it. If you need help, please don't hesitate to ask ...

**Comment by Connum** [comment]
I implemented `unbzip2-stream` and `node-osm-stream` quite quickly, but as you suspected, the performance in general is not enough to handle such huge files, so there's not really a benefit to using it over the regular file opening mechanisms. I guess the lib would have to be implemented as a native module to boost performance. I guess I'll have to find another way, maybe by slicing the data into smaller chunks somehow.
